Repository higherkindness/mu-scala, pull requests merged in 2018-05, with the labels that each got.

#259 Check if file exists before unzipping in idlgen plugin
  modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
Labels: in progress

#256 New example: TodoList application
  build.sbt
  modules/examples/todolist/README.md
  modules/examples/todolist/client/src/main/resources/application.conf
  modules/examples/todolist/client/src/main/scala/ClientApp.scala
  modules/examples/todolist/client/src/main/scala/ClientProgram.scala
  modules/examples/todolist/client/src/main/scala/clients/PingPongClient.scala
  modules/examples/todolist/client/src/main/scala/clients/TagClient.scala
  modules/examples/todolist/client/src/main/scala/clients/TodoItemClient.scala
  modules/examples/todolist/client/src/main/scala/clients/TodoListClient.scala
  modules/examples/todolist/client/src/main/scala/handlers/PingPongClientHandler.scala
  modules/examples/todolist/client/src/main/scala/handlers/TagClientHandler.scala
  modules/examples/todolist/client/src/main/scala/handlers/TodoItemClientHandler.scala
  modules/examples/todolist/client/src/main/scala/handlers/TodoListClientHandler.scala
  modules/examples/todolist/client/src/main/scala/implicits.scala
  modules/examples/todolist/protocol/src/main/scala/MessageId.scala
  modules/examples/todolist/protocol/src/main/scala/PingPongProtocol.scala
  modules/examples/todolist/protocol/src/main/scala/Protocols.scala
  modules/examples/todolist/protocol/src/main/scala/TagProtocol.scala
  modules/examples/todolist/protocol/src/main/scala/TodoItemProtocol.scala
  modules/examples/todolist/protocol/src/main/scala/TodoListProtocol.scala
  modules/examples/todolist/runtime/src/main/scala/CommonRuntime.scala
  modules/examples/todolist/server/src/main/resources/application.conf
  modules/examples/todolist/server/src/main/scala/ServerApp.scala
  modules/examples/todolist/server/src/main/scala/handlers/PingPongServiceHandler.scala
  modules/examples/todolist/server/src/main/scala/handlers/TagRpcServiceHandler.scala
  modules/examples/todolist/server/src/main/scala/handlers/TodoItemRpcServiceHandler.scala
  modules/examples/todolist/server/src/main/scala/handlers/TodoListRpcServiceHandler.scala
  modules/examples/todolist/server/src/main/scala/implicits.scala
  project/ProjectPlugin.scala
  project/plugins.sbt
Labels: code review

#258 Implemented error handling for unary and streaming REST services
  modules/http/server/src/main/scala/HttpConfig.scala
  modules/http/server/src/main/scala/HttpServerBuilder.scala
  modules/http/server/src/main/scala/HttpServerStream.scala
  modules/http/server/src/test/scala/GreeterHandlers.scala
  modules/http/server/src/test/scala/GreeterRestClients.scala
  modules/http/server/src/test/scala/GreeterRestServices.scala
  modules/http/server/src/test/scala/GreeterRestTests.scala
  modules/http/server/src/test/scala/GreeterServices.scala
  modules/http/server/src/test/scala/Util.scala
  modules/http/server/src/test/scala/Utils.scala
  modules/http/server/src/test/scala/logback-test.xml
  project/ProjectPlugin.scala
Labels: in progress

#271 BigDecimal serialization in protobuf and avro
  modules/internal/src/main/scala/encoders.scala
  modules/internal/src/test/scala/util/BigDecimalUtilTest.scala
  modules/server/src/test/scala/protocol/RPCBigDecimalTests.scala
  modules/server/src/test/scala/protocol/RPCTests.scala
  modules/server/src/test/scala/protocol/Utils.scala
Labels: code review

#273 Support for serializing LocalDate and LocalDateTime values
  modules/internal/src/main/scala/encoders.scala
  modules/internal/src/main/scala/util/JavaTimeUtil.scala
  modules/internal/src/test/scala/util/JavaTimeUtilTests.scala
  modules/server/src/test/scala/protocol/RPCJavaTimeTests.scala
Labels: in progress

#275 Release 0.13.5
  version.sbt
Labels: ready
