Repository higherkindness/mu-scala, pull requests merged in 2018-04, with the labels that each got.

#211 Dependency updates
  project/ProjectPlugin.scala
  project/build.properties
Labels: in progress

#212 Release 0.13.0
  version.sbt
Labels: in progress

#214 Releases the plugin first, then the core
  .travis.yml
Labels: in progress

#216 Enable conditionally disabling certain tests in Travis
  modules/common/src/test/scala/RpcBaseTestSuite.scala
  modules/prometheus/client/src/test/scala/BaseMonitorClientInterceptorTests.scala
  modules/prometheus/server/src/test/scala/BaseMonitorServerInterceptorTests.scala
  modules/server/src/test/scala/fs2/RPCTests.scala
  modules/server/src/test/scala/protocol/RPCTests.scala
Labels: in progress

#223 Create example structure
  build.sbt
  modules/examples/routeguide/client/src/main/scala/Client.scala
  modules/examples/routeguide/protocol/src/main/scala/Protocol.scala
  modules/examples/routeguide/server/src/main/scala/Server.scala
  modules/examples/routeguide/service/src/main/scala/Service.scala
Labels: in progress

#230 Spins up gRPC Servers forName
  modules/server/src/test/scala/avro/RPCTests.scala
  modules/server/src/test/scala/avro/Utils.scala
  modules/testing/src/test/scala/ServerChannel.scala
Labels: in progress

#234 Releases Freestyle RPC 0.13.2
  version.sbt
Labels: in progress

#231 Create example route guide client module
  build.sbt
  modules/examples/routeguide/client/src/main/resources/application.conf
  modules/examples/routeguide/client/src/main/scala/ClientProgram.scala
  modules/examples/routeguide/client/src/main/scala/handlers/RouteGuideClientHandler.scala
  modules/examples/routeguide/client/src/main/scala/io/ClientAppIO.scala
  modules/examples/routeguide/client/src/main/scala/io/ClientIO.scala
  modules/examples/routeguide/client/src/main/scala/runtime/ClientConf.scala
  modules/examples/routeguide/client/src/main/scala/task/ClientAppTask.scala
  modules/examples/routeguide/client/src/main/scala/task/ClientTask.scala
Labels: code review

#232 Create example route guide server module
  build.sbt
  modules/examples/routeguide/server/src/main/resources/application.conf
  modules/examples/routeguide/server/src/main/resources/logback.xml
  modules/examples/routeguide/server/src/main/resources/route_guide_db.json
  modules/examples/routeguide/server/src/main/scala/handlers/RouteGuideServiceHandler.scala
  modules/examples/routeguide/server/src/main/scala/io/ServerAppIO.scala
  modules/examples/routeguide/server/src/main/scala/io/ServerIO.scala
Labels: code review

#236 Add route guide example
  README.md
  build.sbt
  docs/src/main/tut/README.md
  docs/src/main/tut/annotations.md
  docs/src/main/tut/core-concepts.md
  docs/src/main/tut/idl-generation.md
  docs/src/main/tut/metrics-reporting.md
  docs/src/main/tut/patterns.md
  docs/src/main/tut/quickstart.md
  docs/src/main/tut/references.md
  docs/src/main/tut/ssl-tls.md
  docs/src/main/tut/streaming.md
  modules/client-netty/src/main/scala/NettyChannelConfig.scala
  modules/client-netty/src/main/scala/netty.scala
  modules/client-netty/src/test/scala/ManagedChannelInterpreterNettyTests.scala
  modules/client/src/main/scala/ManagedChannelConfig.scala
  modules/client/src/main/scala/package.scala
  modules/client/src/test/scala/ManagedChannelInterpreterTests.scala
  modules/client/src/test/scala/RpcClientTestSuite.scala
  modules/examples/routeguide/README.md
  modules/examples/routeguide/client/src/main/resources/application.conf
  modules/examples/routeguide/client/src/main/scala-io/ClientAppIO.scala
  modules/examples/routeguide/client/src/main/scala-io/implicitsio.scala
  modules/examples/routeguide/client/src/main/scala-task/ClientAppTask.scala
  modules/examples/routeguide/client/src/main/scala-task/implicitstask.scala
  modules/examples/routeguide/client/src/main/scala/ClientProgram.scala
  modules/examples/routeguide/client/src/main/scala/handlers/RouteGuideClientHandler.scala
  modules/examples/routeguide/client/src/main/scala/runtime/ClientConf.scala
  modules/examples/routeguide/common/src/main/resources/logback.xml
  modules/examples/routeguide/common/src/main/resources/route_guide_db.json
  modules/examples/routeguide/common/src/main/scala/Codecs.scala
  modules/examples/routeguide/common/src/main/scala/Utils.scala
  modules/examples/routeguide/protocol/src/main/resources/avro/service.avpr
  modules/examples/routeguide/protocol/src/main/resources/proto/service.proto
  modules/examples/routeguide/protocol/src/main/scala/Protocols.scala
  modules/examples/routeguide/runtime/src/main/scala/RouteGuide.scala
  modules/examples/routeguide/server/src/main/resources/application.conf
  modules/examples/routeguide/server/src/main/scala/ServerApp.scala
  modules/examples/routeguide/server/src/main/scala/handlers/RouteGuideServiceHandler.scala
  modules/examples/routeguide/server/src/main/scala/implicits.scala
  modules/internal/src/main/scala/service.scala
  modules/prometheus/client/src/test/scala/InterceptorsRuntime.scala
  modules/server/src/test/scala/protocol/RPCTests.scala
  modules/ssl/src/test/scala/RPCTests.scala
  project/ProjectPlugin.scala
Labels: code review

#238 fixing shutdown hook to run shutdown of server
  modules/server/src/main/scala/handlers/GrpcServerHandler.scala
Labels: in progress

#243 Allow a sequence of source generated directories
  docs/src/main/tut/idl-generation.md
  modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/build.sbt
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/project/build.properties
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/project/plugins.sbt
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/src/main/resources/domain/Domain.avdl
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/src/main/resources/protocol/Protocol.avdl
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/test
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromJars/build.sbt
  modules/server/src/test/scala/fs2/RPCTests.scala
Labels: code review

#244 Adds support for Marshalling/Unmarshalling BigDecimals
  modules/internal/src/main/scala/encoders.scala
  modules/internal/src/main/scala/util/BigDecimalUtil.scala
  modules/internal/src/test/scala/util/BigDecimalUtilTest.scala
  modules/server/src/test/scala/protocol/RPCTests.scala
  modules/server/src/test/scala/protocol/Utils.scala
Labels: code review

#246 Allows generating code from IDL in jars and submodules
  modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
Labels: in progress

#247 IDL definitions packaging from different sources
  docs/src/main/tut/idl-generation.md
  modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/build.sbt
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromJars/build.sbt
Labels: code review

#248 Code Generation from IDL definitions placed in different sources
  docs/src/main/tut/idl-generation.md
  modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/build.sbt
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromJars/build.sbt
Labels: in progress

#249 Fixes Server Helper. Releases 0.13.3.
  modules/examples/routeguide/client/src/main/scala-io/ClientAppIO.scala
  modules/examples/routeguide/client/src/main/scala-task/ClientAppTask.scala
  modules/server/src/main/scala/GrpcServer.scala
  modules/server/src/test/scala/server/HelperTests.scala
  project/ProjectPlugin.scala
  project/build.properties
  version.sbt
Labels: in progress

#252 Added tests for RPC error handling, and a fix for StatusRuntimeException
  modules/internal/src/main/scala/server/monixCalls.scala
  modules/server/src/test/scala/fs2/RPCTests.scala
  modules/server/src/test/scala/fs2/Utils.scala
  modules/server/src/test/scala/protocol/RPCTests.scala
  modules/server/src/test/scala/protocol/Utils.scala
Labels: in progress

#251 Basic ping pong service
  build.sbt
  modules/examples/todolist/README.md
  modules/examples/todolist/client/src/main/resources/application.conf
  modules/examples/todolist/client/src/main/scala/ClientApp.scala
  modules/examples/todolist/client/src/main/scala/ClientProgram.scala
  modules/examples/todolist/client/src/main/scala/handlers/PingPongClientHandler.scala
  modules/examples/todolist/client/src/main/scala/implicits.scala
  modules/examples/todolist/client/src/main/scala/runtime/ClientConf.scala
  modules/examples/todolist/protocol/src/main/scala/Protocols.scala
  modules/examples/todolist/runtime/src/main/scala/PingPong.scala
  modules/examples/todolist/server/src/main/resources/application.conf
  modules/examples/todolist/server/src/main/scala/ServerApp.scala
  modules/examples/todolist/server/src/main/scala/handlers/PingPongServiceHandler.scala
  modules/examples/todolist/server/src/main/scala/implicits.scala
  project/ProjectPlugin.scala
Labels: code review

#254 Removes the IDL core Dependency
  modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/build.sbt
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromJars/build.sbt
Labels: code review, enhancement

#257 Minor Todolist Example Improvements
  modules/examples/todolist/client/src/main/scala/ClientProgram.scala
  modules/examples/todolist/client/src/main/scala/handlers/PingPongClientHandler.scala
  modules/examples/todolist/client/src/main/scala/handlers/TagClientHandler.scala
  modules/examples/todolist/client/src/main/scala/handlers/TodoItemClientHandler.scala
  modules/examples/todolist/client/src/main/scala/handlers/TodoListClientHandler.scala
  modules/examples/todolist/client/src/main/scala/implicits.scala
  modules/examples/todolist/protocol/src/main/scala/MessageId.scala
  modules/examples/todolist/protocol/src/main/scala/PingPongProtocol.scala
  modules/examples/todolist/protocol/src/main/scala/Protocols.scala
  modules/examples/todolist/protocol/src/main/scala/TagProtocol.scala
  modules/examples/todolist/protocol/src/main/scala/TodoItemProtocol.scala
  modules/examples/todolist/protocol/src/main/scala/TodoListProtocol.scala
  modules/examples/todolist/runtime/src/main/scala/CommonRuntime.scala
  modules/examples/todolist/runtime/src/main/scala/PingPong.scala
  modules/examples/todolist/server/src/main/scala/handlers/PingPongServiceHandler.scala
  modules/examples/todolist/server/src/main/scala/handlers/TagRpcServiceHandler.scala
  modules/examples/todolist/server/src/main/scala/handlers/TodoItemRpcServiceHandler.scala
  modules/examples/todolist/server/src/main/scala/handlers/TodoListRpcServiceHandler.scala
  modules/examples/todolist/server/src/main/scala/implicits.scala
Labels: in progress
