Repository higherkindness/mu-scala, pull requests merged in 2018-03, with the labels that each got.

#187 Project Upgrade
  modules/internal/src/main/scala/encoders.scala
  project/ProjectPlugin.scala
  project/build.properties
  project/plugins.sbt
Labels: in progress

#189 Fixed stacktraces in tests caused by unclosed channels
  modules/client-netty/src/test/scala/ManagedChannelInterpreterNettyTests.scala
  modules/client/src/test/scala/ManagedChannelInterpreterTests.scala
  modules/server/src/test/scala/CommonUtils.scala
Labels: in progress

#188 sbt build config refactoring, with dependency updates
  project/ProjectPlugin.scala
  project/plugins.sbt
Labels: in progress

#193 Upgrades to Freestyle 0.8.0
  modules/server/src/main/scala/GrpcServer.scala
  modules/server/src/test/scala/protocol/Utils.scala
  project/ProjectPlugin.scala
Labels: in progress

#194 Fixes Snapshot Publish
  .travis.yml
Labels: in progress

#196 Fixes links references in every MD document
  docs/src/main/tut/README.md
  docs/src/main/tut/annotations.md
  docs/src/main/tut/core-concepts.md
  docs/src/main/tut/idl-generation.md
  docs/src/main/tut/metrics-reporting.md
  docs/src/main/tut/patterns.md
  docs/src/main/tut/quickstart.md
  docs/src/main/tut/references.md
  docs/src/main/tut/ssl-tls.md
  docs/src/main/tut/streaming.md
Labels: in progress

#197 Adds some changes to the core-concepts and streaming docs
  docs/src/main/tut/README.md
  docs/src/main/tut/core-concepts.md
  docs/src/main/tut/idl-generation.md
  docs/src/main/tut/metrics-reporting.md
  docs/src/main/tut/patterns.md
  docs/src/main/tut/ssl-tls.md
  docs/src/main/tut/streaming.md
Labels: in progress

#190 [Docs] Split into different sections
  docs/src/main/tut/README.md
  docs/src/main/tut/annotations.md
  docs/src/main/tut/core-concepts.md
  docs/src/main/tut/idl-generation.md
  docs/src/main/tut/metrics-reporting.md
  docs/src/main/tut/patterns.md
  docs/src/main/tut/quickstart.md
  docs/src/main/tut/references.md
  docs/src/main/tut/ssl-tls.md
  docs/src/main/tut/streaming.md
Labels: WIP, in progress

#195 Avro IDL Support
  build.sbt
  docs/src/main/tut/annotations.md
  docs/src/main/tut/core-concepts.md
  docs/src/main/tut/idl-generation.md
  docs/src/main/tut/metrics-reporting.md
  docs/src/main/tut/patterns.md
  docs/src/main/tut/quickstart.md
  docs/src/main/tut/ssl-tls.md
  docs/src/main/tut/streaming.md
  modules/common/src/main/scala/protocol.scala
  modules/idlgen/core/src/main/scala/Application.scala
  modules/idlgen/core/src/main/scala/AvroGenerator.scala
  modules/idlgen/core/src/main/scala/Generator.scala
  modules/idlgen/core/src/main/scala/Model.scala
  modules/idlgen/core/src/main/scala/Parser.scala
  modules/idlgen/core/src/main/scala/ProtoGenerator.scala
  modules/idlgen/core/src/test/resources/GreeterService.scala
  modules/idlgen/core/src/test/resources/avro/GreeterService.avpr
  modules/idlgen/core/src/test/resources/proto/GreeterService.proto
  modules/idlgen/core/src/test/scala/IdlGenTests.scala
  modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
  modules/internal/src/main/scala/util/FileUtil.scala
  modules/internal/src/main/scala/util/ScalametaUtil.scala
  project/ProjectPlugin.scala
Labels: in progress

#198 Releases frees-rpc 0.12.0
  version.sbt
Labels: in progress

#202 Fixes title formatting in SSL/TLS
  docs/src/main/tut/ssl-tls.md
Labels: in progress

#204 Fixes `idlgen-sbt` release Process in Travis
  .travis.yml
Labels: in progress

#203 Hello, Http Server integration
  build.sbt
  modules/http/server/src/main/scala/HttpConfig.scala
  modules/http/server/src/main/scala/HttpServerBuilder.scala
  modules/http/server/src/main/scala/HttpServerStream.scala
  modules/http/server/src/test/scala/ExampleService.scala
  modules/http/server/src/test/scala/HttpServerTests.scala
  project/ProjectPlugin.scala
Labels: in progress

#207 Solves encoding issues in docs
  docs/src/main/tut/core-concepts.md
  docs/src/main/tut/ssl-tls.md
  docs/src/main/tut/streaming.md
Labels: code review

#208 Fixes in idlGen header, docs and tests
  docs/src/main/tut/idl-generation.md
  modules/idlgen/core/src/main/scala/Application.scala
  modules/idlgen/core/src/main/scala/ProtoGenerator.scala
  modules/idlgen/core/src/test/resources/proto/GreeterService.proto
  modules/idlgen/core/src/test/scala/IdlGenTests.scala
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/.gitignore
  modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/test
Labels: in progress

#209 Ignore intermittently-failing tests on Travis
  modules/prometheus/client/src/test/scala/BaseMonitorClientInterceptorTests.scala
  modules/prometheus/server/src/test/scala/BaseMonitorServerInterceptorTests.scala
Labels: in progress
